FROM rust:1.98.0-trixie@sha256:620dbcd124499c59e2406d3741574b5c5838cf9eb9656f0c3a03948f79b02959

RUN rustup component add rustfmt clippy

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        g++ \
        git \
        libclang-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/magma-search
