[package]
name = "magma-sat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
magma-core = { path = "../magma-core", features = ["sat"] }
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
rustsat.workspace = true
rustsat-cadical.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
